### ISSUE TITLE
Interested In This Api

### ISSUE THREAD

**Issue by VampyreBatz** [theshadow76/PocketOptionAPI#6]
Whats going on with this api? how far along is this?

**Comment by theshadow76** [comment]
The api is in development, just that I did not had the time latetly, but in a few days I'll get back to it!

**Comment by theshadow76** [comment]
If you have any more questions, contact me in Instagram
At: vigo_walker

**Comment by VampyreBatz** [comment]
inbox sent

**Comment by theshadow76** [comment]
Try this: https://github.com/ChipaDevTeam/BinaryOptionsTools-v2
